
delete T_Reprocessed_Scopes where REPROCESSED_SCOPES_KEY>100 and REPROCESSED_SCOPES_KEY<200;
delete t_reprocess_condition where REPROCESS_CONDITION_KEY>100 and REPROCESS_CONDITION_KEY<200;
delete T_Reprocessor_Info where REPROCESSOR_INFO_KEY>100 and REPROCESSOR_INFO_KEY<200;
commit;
insert into T_Reprocessor_Info(REPROCESSOR_INFO_KEY,REPROCESSOR_KEY,VERSION,DISINFECT_BOTTLECOUNT,REPROCESS_USED_COUNT,REPROCESSOR_STATUS_KEY,DISINFECTION_OPERATION_COUNT,DISINFECTION_ELAPSED_DAY_COUNT,TIME_LAG_MINUTES,NOTIFICATION_HIDE_FLG)
values(101,1,'3.03',2,19,4,15,3,0,0);
insert into T_Reprocessor_Info(REPROCESSOR_INFO_KEY,REPROCESSOR_KEY,VERSION,DISINFECT_BOTTLECOUNT,REPROCESS_USED_COUNT,REPROCESSOR_STATUS_KEY,DISINFECTION_OPERATION_COUNT,DISINFECTION_ELAPSED_DAY_COUNT,TIME_LAG_MINUTES,NOTIFICATION_HIDE_FLG)
values(102,2,'3.03',3,139,4,15,3,0,0);
commit;

--reprocessing normal 
insert into T_Reprocess_Condition(REPROCESS_CONDITION_KEY,AUTO_DETECTED_FLG,REPROCESSOR_KEY,REPROCESS_START_DATE,REPROCESS_END_DATE,PROGRAM_NO,SCOPEWASH_TIME_SETTING,DISINFECT_TIME_SETTING,DISINFECT_TEMPERATURE_SETTING,LEAK_AND_ALCOHOL,WATER_TEMPERATURE,DISINFECT_TEMPERATURE,DISINFECT_COUNT,DISINFECT_PASTDATE,TOTAL_WASH_COUNT,WATERSUPPLY_TIME,START_PERSON_KEY,END_PERSON_KEY,
DELETED_FLG,REPROCESS_RESULT_KEY,REPROCESSOR_PROGRAMS_KEY,AUTO_REGISTERD_FROM_DC_FLG,ALCOHOL_FLUSH_KEY,REPROCESSING_ROOM_KEY,LOCK_VERSION, CREATED_DATE_TIME)
values (101,1,1,'16-Jun-16 07.15 AM','16-Jun-16 07.46 AM',1,3,7,20,2,21,21,99,99,19,68,101,101,0,3,11,1,2,1,0,'16-JUN-16 07.46.28.098000000 AM');
--reprocessing stopped with errors
insert into T_Reprocess_Condition(REPROCESS_CONDITION_KEY,AUTO_DETECTED_FLG,REPROCESSOR_KEY,REPROCESS_START_DATE,REPROCESS_END_DATE,PROGRAM_NO,SCOPEWASH_TIME_SETTING,DISINFECT_TIME_SETTING,DISINFECT_TEMPERATURE_SETTING,LEAK_AND_ALCOHOL,WATER_TEMPERATURE,DISINFECT_TEMPERATURE,DISINFECT_COUNT,DISINFECT_PASTDATE,TOTAL_WASH_COUNT,WATERSUPPLY_TIME,START_PERSON_KEY,END_PERSON_KEY,
DELETED_FLG,REPROCESS_RESULT_KEY,REPROCESSOR_PROGRAMS_KEY,AUTO_REGISTERD_FROM_DC_FLG,ALCOHOL_FLUSH_KEY,REPROCESSING_ROOM_KEY,LOCK_VERSION, CREATED_DATE_TIME,ERROR_VALUE,ERROR_CODE,PROGRESS_NO,PROGRESS_PASTTIME)
values (102,1,2,'16-Jun-16 07.22 AM','16-Jun-16 07.25 AM',2,3,7,20,2,21,21,99,99,139,68,101,101,0,2,11,1,2,1,0,'16-JUN-16 07.22.28.098000000 AM','ffffffffffffffffffffffff',0,'100E',182);
commit;

insert into T_Reprocessed_Scopes (REPROCESSED_SCOPES_KEY,REPROCESS_CONDITION_KEY,INDEX_NO,SCOPE_KEY,ASSOCIATED_STATUS,AUTO_REGISTERD_FROM_DC_FLG,START_PERSON_KEY,END_PERSON_KEY,NOTIFICATION_HIDE_FLG,DELETED_FLG)
values (101,101,1,101,0,1,101,101,0,0);
--scopes that had errors when reprocessed
insert into T_Reprocessed_Scopes (REPROCESSED_SCOPES_KEY,REPROCESS_CONDITION_KEY,INDEX_NO,SCOPE_KEY,ASSOCIATED_STATUS,AUTO_REGISTERD_FROM_DC_FLG,START_PERSON_KEY,END_PERSON_KEY,NOTIFICATION_HIDE_FLG,DELETED_FLG)
values (102,102,1,102,0,1,101,101,0,0);
insert into T_Reprocessed_Scopes (REPROCESSED_SCOPES_KEY,REPROCESS_CONDITION_KEY,INDEX_NO,SCOPE_KEY,ASSOCIATED_STATUS,AUTO_REGISTERD_FROM_DC_FLG,START_PERSON_KEY,END_PERSON_KEY,NOTIFICATION_HIDE_FLG,DELETED_FLG)
values (103,102,2,103,0,1,101,101,0,0);
commit;


